Document the --hypothesis-strategy cli param
chaostoolkit/chaostoolkit-documentation pull request #106
Opened 2021-07-27 23:17 UTC by adamdabbracci

Signed-off-by: Adam D'Abbracci <adamdabbracci@adams-mbp.lan>

2021-07-29 09:21 UTC, ciaranevans requested changes
Thanks for the contribution @adamdabbracci!

Looks good to me apart from the small typo!

2021-07-29 09:21 UTC, ciaranevans commented on sources/reference/usage/run.md
> +By default, the steady state will be tested before and after an experiment runs. However, you can specify a different strategy through the `--hypothesis-strategy` parmeter. The options are:
```suggestion
By default, the steady state will be tested before and after an experiment runs. However, you can specify a different strategy through the `--hypothesis-strategy` parameter. The options are:
```

2021-07-29 14:25 UTC, ciaranevans commented
@adamdabbracci 👋 Just a reminder that you need to DCO sign **every** commit you push! 

If you're a frequent contributor to our repos, what I've done is setup a commit template in my `chaostoolkit/` dir with:

```
Signed-off-by: Ciaran Evans <ciaran@reliably.com>
```

In a file called `chaostoolkit-commit-template.txt`

You can then set it to just the local dir by:

```
git config --local commit.template fully/qualified/path/to/template/file
```

2021-07-30 00:09 UTC, adamdabbracci commented
Whoops! I committed your fix directly from the UI, so I completely forgot about the DCO. I've tried to sign it for that commit, but it doesn't seem to be picking up, so I must be missing something obvious.

Checkout the PR:
`gh pr checkout 106 -R chaostoolkit/chaostoolkit-documentation`

Sign off:
`git commit --amend --no-edit --signoff`

Push:
`git push --force-with-lease origin add-hypothesis-strategy`

2021-07-30 08:01 UTC, ciaranevans commented
I wonder if it's something silly like we're both on the commit or something! I'll have a look!

2021-07-30 08:05 UTC, ciaranevans commented
@adamdabbracci are you signing off with an email that is available on your GitHub Account?

Just looking at the UI above, the pushes are assigned to you, but the commits appear to be profile-less

Can you double check that your email is listed here https://github.com/settings/emails?

2021-07-31 13:31 UTC, adamdabbracci commented
I'm going to close this PR and open a new one... with the signature correct from the beginning hopefully... thank you for trying to troubleshoot!

2021-07-31 13:31 UTC, closed without merging